=== martin-vi/deegree-tilestore-cassandra/src/main/resources/META-INF/schemas/datasource/tile/cassandra/3.2.0/cassandra.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.w3.org/2001/XMLSchema" xmlns:md="http://www.deegree.org/metadata/spatial"
  targetNamespace="http://www.deegree.org/datasource/tile/cassandra" xmlns:t="http://www.deegree.org/datasource/tile/cassandra"
  elementFormDefault="qualified" xmlns:jaxb="http://java.sun.com/xml/ns/jaxb" jaxb:version="2.1">
  <import namespace="http://www.deegree.org/metadata/spatial" schemaLocation="http://schemas.deegree.org/commons/spatialmetadata/3.1.0/spatialmetadata.xsd" />
  <annotation>
    <appinfo>
      <jaxb:schemaBindings>
        <jaxb:package name="org.deegree.tile.persistence.cassandra.jaxb" />
      </jaxb:schemaBindings>
    </appinfo>
  </annotation>
  <element name="CassandraTileStore">
    <annotation>
      <documentation>TileStore that is backed by a directory of image blobs in the cassandra database.</documentation>
      <appinfo>
        <jaxb:class name="CassandraTileStoreJAXB" />
      </appinfo>
    </annotation>
    <complexType>
      <sequence maxOccurs="unbounded">
        <element name="TileDataSet">
          <complexType>
            <sequence>
              <element name="Identifier" type="string" minOccurs="0">
                <annotation>
                  <documentation>Uses the name of the layer directory by default</documentation>
                </annotation>
              </element>
              <element name="TileMatrixSetId" type="string" />
              <element name="CassandraColumnfamily" type="string" />
              <element name="writeTimestamp" type="boolean" minOccurs="0" maxOccurs="1" />
            </sequence>
          </complexType>
        </element>
      </sequence>
      <attribute name="configVersion" use="required" fixed="3.2.0" />
      <attribute name="CassandraHosts" use="required" type="string" />
      <attribute name="CassandraKeyspace" use="required" type="string" />            
    </complexType>
  </element>
</schema>

=== martin-vi/deegree-tilestore-cassandra/src/main/resources/META-INF/schemas/datasource/tile/cassandra/3.2.0/example.xml
<?xml version="1.0"?>
<CassandraTileStore xmlns="http://www.deegree.org/datasource/tile/cassandra" xmlns:md="http://www.deegree.org/metadata/spatial"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.deegree.org/datasource/tile/cassandra http://schemas.deegree.org/datasource/tile/filesystem/3.2.0/cassandra.xsd"
  configVersion="3.2.0">

  <TileDataSet>
    <Identifier>cassandra</Identifier>
    <TileMatrixSetId>inspirecrs84quad</TileMatrixSetId>
    <CassandraHosts>localhost:9160,otherhost:9160</CassandraHosts>
    <CassandraCluster>Test Cluster</CassandraCluster>
    <CassandraKeyspace>tilecache</CassandraKeyspace>
    <CassandraColumnfamily>tilecache</CassandraColumnfamily>
  </TileDataSet>

</CassandraTileStore>
